/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TicTacToePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// modal.ts
var import_obsidian = require("obsidian");

// ai.ts
var WINNING_PATTERNS = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],
  [0, 4, 8],
  [2, 4, 6]
];
function checkWin(board, symbol) {
  return WINNING_PATTERNS.some((pattern) => pattern.every((idx) => board[idx] === symbol));
}
function checkWinningLine(board, symbol) {
  for (const pattern of WINNING_PATTERNS) {
    if (pattern.every((idx) => board[idx] === symbol)) {
      return pattern;
    }
  }
  return null;
}
function isBoardFull(board) {
  return board.every((cell) => cell !== null);
}
function getRandomMove(board) {
  const emptySpots = [];
  board.forEach((cell, idx) => {
    if (cell === null)
      emptySpots.push(idx);
  });
  if (emptySpots.length === 0)
    return -1;
  const randomIndex = Math.floor(Math.random() * emptySpots.length);
  return emptySpots[randomIndex];
}
function getSmartMove(board, aiSymbol, playerSymbol) {
  const b = [...board];
  for (let i = 0; i < 9; i++) {
    if (b[i] === null) {
      b[i] = aiSymbol;
      if (checkWin(b, aiSymbol)) {
        return i;
      }
      b[i] = null;
    }
  }
  for (let i = 0; i < 9; i++) {
    if (b[i] === null) {
      b[i] = playerSymbol;
      if (checkWin(b, playerSymbol)) {
        return i;
      }
      b[i] = null;
    }
  }
  if (b[4] === null) {
    return 4;
  }
  const corners = [0, 2, 6, 8];
  const emptyCorners = corners.filter((idx) => b[idx] === null);
  if (emptyCorners.length > 0) {
    const randomCornerIdx = Math.floor(Math.random() * emptyCorners.length);
    return emptyCorners[randomCornerIdx];
  }
  const sides = [1, 3, 5, 7];
  const emptySides = sides.filter((idx) => b[idx] === null);
  if (emptySides.length > 0) {
    const randomSideIdx = Math.floor(Math.random() * emptySides.length);
    return emptySides[randomSideIdx];
  }
  return -1;
}
function minimax(b, depth, isMax, aiSymbol, playerSymbol) {
  if (checkWin(b, aiSymbol))
    return 10 - depth;
  if (checkWin(b, playerSymbol))
    return depth - 10;
  if (isBoardFull(b))
    return 0;
  if (isMax) {
    let best = -Infinity;
    for (let i = 0; i < 9; i++) {
      if (b[i] === null) {
        b[i] = aiSymbol;
        const score = minimax(b, depth + 1, false, aiSymbol, playerSymbol);
        b[i] = null;
        best = Math.max(best, score);
      }
    }
    return best;
  } else {
    let best = Infinity;
    for (let i = 0; i < 9; i++) {
      if (b[i] === null) {
        b[i] = playerSymbol;
        const score = minimax(b, depth + 1, true, aiSymbol, playerSymbol);
        b[i] = null;
        best = Math.min(best, score);
      }
    }
    return best;
  }
}
function getUnbeatableMove(board, aiSymbol, playerSymbol) {
  let bestVal = -Infinity;
  let bestMove = -1;
  const b = [...board];
  for (let i = 0; i < 9; i++) {
    if (b[i] === null) {
      b[i] = aiSymbol;
      const moveVal = minimax(b, 0, false, aiSymbol, playerSymbol);
      b[i] = null;
      if (moveVal > bestVal) {
        bestVal = moveVal;
        bestMove = i;
      }
    }
  }
  return bestMove;
}

// modal.ts
var TicTacToeModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.board = Array(9).fill(null);
    this.isGameOver = false;
    this.isAiThinking = false;
    this.scores = {
      player: 0,
      ai: 0,
      draws: 0
    };
    this.timerInterval = null;
    this.timeLeft = 0;
    this.cellEls = [];
    this.plugin = plugin;
    this.difficulty = this.plugin.settings.difficulty;
    this.playerSymbol = this.plugin.settings.playerSymbol;
    this.aiSymbol = this.playerSymbol === "X" ? "O" : "X";
    this.autoReset = this.plugin.settings.autoReset;
    this.pomodoroMode = this.plugin.settings.pomodoroMode;
    this.pomodoroTime = this.plugin.settings.pomodoroTime;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.mainContainerEl = contentEl.createDiv({ cls: "ttt-container" });
    this.mainContainerEl.createDiv({ cls: "ttt-title", text: "Tic-Tac-Toe Brain" });
    this.statusEl = this.mainContainerEl.createDiv({ cls: "ttt-status", text: "\u0412\u0430\u0448 \u0445\u043E\u0434 (\u274C)" });
    this.updateStatusClass();
    const scoreboard = this.mainContainerEl.createDiv({ cls: "ttt-scoreboard" });
    const playerCard = scoreboard.createDiv({ cls: "ttt-score-card" });
    playerCard.createDiv({ cls: "ttt-score-label", text: `\u0418\u0433\u0440\u043E\u043A (${this.playerSymbol})` });
    this.scorePlayerEl = playerCard.createDiv({ cls: "ttt-score-value player", text: "0" });
    const drawsCard = scoreboard.createDiv({ cls: "ttt-score-card" });
    drawsCard.createDiv({ cls: "ttt-score-label", text: "\u041D\u0438\u0447\u044C\u0438" });
    this.scoreDrawsEl = drawsCard.createDiv({ cls: "ttt-score-value draws", text: "0" });
    const aiCard = scoreboard.createDiv({ cls: "ttt-score-card" });
    aiCard.createDiv({ cls: "ttt-score-label", text: `\u0418\u0418 (${this.aiSymbol})` });
    this.scoreAiEl = aiCard.createDiv({ cls: "ttt-score-value ai", text: "0" });
    this.timerContainerEl = this.mainContainerEl.createDiv({ cls: "ttt-timer-container" });
    this.timerTextEl = this.timerContainerEl.createSpan({ text: "" });
    const timerBarBg = this.timerContainerEl.createDiv({ cls: "ttt-timer-bar-bg" });
    this.timerBarEl = timerBarBg.createDiv({ cls: "ttt-timer-bar-fill" });
    if (!this.pomodoroMode) {
      this.timerContainerEl.style.display = "none";
    }
    const controls = this.mainContainerEl.createDiv({ cls: "ttt-controls" });
    const diffRow = controls.createDiv({ cls: "ttt-control-row" });
    diffRow.createDiv({ cls: "ttt-control-label", text: "\u0421\u043B\u043E\u0436\u043D\u043E\u0441\u0442\u044C \u0418\u0418" });
    const diffSelect = diffRow.createEl("select", { cls: "ttt-select" });
    diffSelect.createEl("option", { value: "random", text: "\u0421\u043B\u0443\u0447\u0430\u0439\u043D\u044B\u0439" });
    diffSelect.createEl("option", { value: "smart", text: "\u0423\u043C\u043D\u044B\u0439" });
    diffSelect.createEl("option", { value: "unbeatable", text: "\u041D\u0435\u043F\u0440\u043E\u0438\u0433\u0440\u044B\u0432\u0430\u0435\u043C\u044B\u0439" });
    diffSelect.value = this.difficulty;
    diffSelect.addEventListener("change", (e) => {
      this.difficulty = e.target.value;
      this.resetGame(false);
    });
    const symbolRow = controls.createDiv({ cls: "ttt-control-row" });
    const symbolLabelContainer = symbolRow.createDiv({ cls: "ttt-control-label" });
    symbolLabelContainer.createSpan({ text: "\u0412\u0430\u0448 \u0441\u0438\u043C\u0432\u043E\u043B" });
    this.energyBadgeEl = symbolLabelContainer.createSpan({
      cls: "ttt-energy-badge",
      text: `\u26A1 ${this.plugin.settings.energy}`
    });
    const symbolToggle = symbolRow.createDiv({ cls: "ttt-symbol-toggle" });
    const btnX = symbolToggle.createEl("button", {
      cls: `ttt-symbol-btn ${this.playerSymbol === "X" ? "active" : ""}`,
      text: "X"
    });
    const btnO = symbolToggle.createEl("button", {
      cls: `ttt-symbol-btn ${this.playerSymbol === "O" ? "active" : ""}`,
      text: "O"
    });
    btnX.addEventListener("click", () => {
      if (this.playerSymbol !== "X") {
        this.playerSymbol = "X";
        this.aiSymbol = "O";
        btnX.addClass("active");
        btnO.removeClass("active");
        this.updateScoreboardLabels();
        this.resetGame(true);
      }
    });
    btnO.addEventListener("click", () => {
      if (this.playerSymbol !== "O") {
        this.playerSymbol = "O";
        this.aiSymbol = "X";
        btnO.addClass("active");
        btnX.removeClass("active");
        this.updateScoreboardLabels();
        this.resetGame(true);
      }
    });
    this.boardEl = this.mainContainerEl.createDiv({ cls: "ttt-board" });
    this.cellEls = [];
    for (let i = 0; i < 9; i++) {
      const cell = this.boardEl.createDiv({ cls: "ttt-cell" });
      cell.addEventListener("click", () => this.handleCellClick(i));
      this.cellEls.push(cell);
    }
    const actions = this.mainContainerEl.createDiv({ cls: "ttt-actions" });
    const newGameBtn = actions.createEl("button", { cls: "ttt-btn", text: "\u041D\u043E\u0432\u0430\u044F \u0438\u0433\u0440\u0430" });
    newGameBtn.addEventListener("click", () => this.resetGame(false));
    const resetScoresBtn = actions.createEl("button", { cls: "ttt-btn ttt-btn-secondary", text: "\u0421\u0431\u0440\u043E\u0441\u0438\u0442\u044C \u0441\u0447\u0451\u0442" });
    resetScoresBtn.addEventListener("click", () => this.resetGame(true));
    this.resetGame(true);
    if (this.pomodoroMode) {
      this.startPomodoroTimer();
    }
  }
  onClose() {
    this.stopPomodoroTimer();
  }
  updateStatusClass() {
    if (this.isGameOver) {
      this.statusEl.addClass("highlight");
    } else {
      this.statusEl.removeClass("highlight");
    }
  }
  updateScoreboardLabels() {
    const cards = this.mainContainerEl.querySelectorAll(".ttt-score-card");
    if (cards.length >= 3) {
      cards[0].querySelector(".ttt-score-label").textContent = `\u0418\u0433\u0440\u043E\u043A (${this.playerSymbol})`;
      cards[2].querySelector(".ttt-score-label").textContent = `\u0418\u0418 (${this.aiSymbol})`;
    }
  }
  startPomodoroTimer() {
    this.stopPomodoroTimer();
    this.timeLeft = this.pomodoroTime;
    this.updateTimerUI();
    this.timerInterval = window.setInterval(() => {
      this.timeLeft--;
      this.updateTimerUI();
      if (this.timeLeft <= 0) {
        this.stopPomodoroTimer();
        this.close();
        new import_obsidian.Notice("\u041E\u0442\u0434\u043E\u0445\u043D\u0443\u043B\u0438? \u041F\u0440\u043E\u0434\u043E\u043B\u0436\u0430\u0439\u0442\u0435 \u0440\u0430\u0431\u043E\u0442\u0443!");
      }
    }, 1e3);
  }
  stopPomodoroTimer() {
    if (this.timerInterval) {
      window.clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
  }
  updateTimerUI() {
    if (!this.pomodoroMode)
      return;
    const minutes = Math.floor(this.timeLeft / 60);
    const seconds = this.timeLeft % 60;
    const timeString = `${minutes}:${seconds < 10 ? "0" : ""}${seconds}`;
    this.timerTextEl.textContent = `\u0422\u0430\u0439\u043C\u0435\u0440: ${timeString}`;
    const percentage = this.timeLeft / this.pomodoroTime * 100;
    this.timerBarEl.style.width = `${percentage}%`;
    this.timerBarEl.removeClass("warning", "danger");
    if (percentage <= 20) {
      this.timerBarEl.addClass("danger");
    } else if (percentage <= 50) {
      this.timerBarEl.addClass("warning");
    }
  }
  handleCellClick(index) {
    if (this.isGameOver || this.isAiThinking || this.board[index] !== null) {
      return;
    }
    this.makeMove(index, this.playerSymbol);
    if (this.checkGameState(this.playerSymbol)) {
      return;
    }
    this.isAiThinking = true;
    this.statusEl.textContent = `\u0418\u0418 (${this.aiSymbol}) \u0434\u0443\u043C\u0430\u0435\u0442...`;
    setTimeout(() => {
      if (this.isGameOver)
        return;
      let aiMove = -1;
      if (this.difficulty === "random") {
        aiMove = getRandomMove(this.board);
      } else if (this.difficulty === "smart") {
        aiMove = getSmartMove(this.board, this.aiSymbol, this.playerSymbol);
      } else if (this.difficulty === "unbeatable") {
        aiMove = getUnbeatableMove(this.board, this.aiSymbol, this.playerSymbol);
      }
      if (aiMove !== -1) {
        this.makeMove(aiMove, this.aiSymbol);
        this.checkGameState(this.aiSymbol);
      }
      this.isAiThinking = false;
    }, 300);
  }
  makeMove(index, symbol) {
    this.board[index] = symbol;
    const cell = this.cellEls[index];
    cell.addClass("occupied");
    const symbolSpan = cell.createSpan({
      cls: `ttt-cell-symbol ${symbol === "X" ? "x-color" : "o-color"}`,
      text: symbol === "X" ? "\u274C" : "\u2B55"
    });
  }
  checkGameState(lastSymbol) {
    const winLine = checkWinningLine(this.board, lastSymbol);
    if (winLine) {
      this.isGameOver = true;
      this.statusEl.textContent = lastSymbol === this.playerSymbol ? "\u0412\u044B \u043F\u043E\u0431\u0435\u0434\u0438\u043B\u0438! \u{1F389}" : "\u0418\u0418 \u043F\u043E\u0431\u0435\u0434\u0438\u043B! \u{1F916}";
      this.updateStatusClass();
      winLine.forEach((idx) => {
        this.cellEls[idx].addClass("winning");
      });
      if (lastSymbol === this.playerSymbol) {
        this.scores.player++;
        this.scorePlayerEl.textContent = this.scores.player.toString();
        if (this.pomodoroMode) {
          this.plugin.settings.energy++;
          this.plugin.saveSettings();
          this.energyBadgeEl.textContent = `\u26A1 ${this.plugin.settings.energy}`;
        }
      } else {
        this.scores.ai++;
        this.scoreAiEl.textContent = this.scores.ai.toString();
      }
      this.triggerAutoReset();
      return true;
    }
    if (isBoardFull(this.board)) {
      this.isGameOver = true;
      this.statusEl.textContent = "\u041D\u0438\u0447\u044C\u044F! \u{1F91D}";
      this.updateStatusClass();
      this.cellEls.forEach((cell) => cell.addClass("draw"));
      this.scores.draws++;
      this.scoreDrawsEl.textContent = this.scores.draws.toString();
      this.triggerAutoReset();
      return true;
    }
    const nextSymbol = lastSymbol === this.playerSymbol ? this.aiSymbol : this.playerSymbol;
    this.statusEl.textContent = nextSymbol === this.playerSymbol ? `\u0412\u0430\u0448 \u0445\u043E\u0434 (${this.playerSymbol === "X" ? "\u274C" : "\u2B55"})` : `\u0425\u043E\u0434 \u0418\u0418 (${this.aiSymbol === "X" ? "\u274C" : "\u2B55"})...`;
    return false;
  }
  triggerAutoReset() {
    if (this.autoReset) {
      setTimeout(() => {
        if (this.isGameOver) {
          this.resetGame(false);
        }
      }, 2e3);
    }
  }
  resetGame(resetAllScores = false) {
    this.board = Array(9).fill(null);
    this.isGameOver = false;
    this.isAiThinking = false;
    this.statusEl.textContent = `\u0412\u0430\u0448 \u0445\u043E\u0434 (${this.playerSymbol === "X" ? "\u274C" : "\u2B55"})`;
    this.updateStatusClass();
    this.cellEls.forEach((cell) => {
      cell.empty();
      cell.removeClass("occupied", "winning", "draw");
    });
    if (resetAllScores) {
      this.scores = { player: 0, ai: 0, draws: 0 };
      this.scorePlayerEl.textContent = "0";
      this.scoreAiEl.textContent = "0";
      this.scoreDrawsEl.textContent = "0";
    }
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  difficulty: "smart",
  playerSymbol: "X",
  autoReset: false,
  pomodoroMode: false,
  pomodoroTime: 120,
  energy: 0
};
var TicTacToePlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "play-tic-tac-toe",
      name: "Play Tic-Tac-Toe",
      callback: () => {
        new TicTacToeModal(this.app, this).open();
      }
    });
    this.addRibbonIcon("gamepad-2", "Play Tic-Tac-Toe", () => {
      new TicTacToeModal(this.app, this).open();
    });
    this.addSettingTab(new TicTacToeSettingTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor("ttt", (source, el, ctx) => {
      let difficulty = this.settings.difficulty;
      let playerSymbol = this.settings.playerSymbol;
      const lines = source.split("\n");
      for (const line of lines) {
        const parts = line.split(":");
        if (parts.length === 2) {
          const key = parts[0].trim().toLowerCase();
          const val = parts[1].trim().toLowerCase();
          if (key === "difficulty" && ["random", "smart", "unbeatable"].includes(val)) {
            difficulty = val;
          }
          if (key === "playersymbol" || key === "symbol" || key === "player-symbol") {
            if (val === "x" || val === "o") {
              playerSymbol = val.toUpperCase();
            }
          }
        }
      }
      const aiSymbol = playerSymbol === "X" ? "O" : "X";
      let board = Array(9).fill(null);
      let isGameOver = false;
      let isAiThinking = false;
      const container = el.createDiv({ cls: "ttt-container ttt-block-container" });
      container.createDiv({ cls: "ttt-title", text: "Tic-Tac-Toe Brain" });
      const status = container.createDiv({
        cls: "ttt-status",
        text: `\u0412\u0430\u0448 \u0445\u043E\u0434 (${playerSymbol === "X" ? "\u274C" : "\u2B55"})`
      });
      const boardEl = container.createDiv({ cls: "ttt-board" });
      const cells = [];
      const updateStatusClass = () => {
        if (isGameOver) {
          status.addClass("highlight");
        } else {
          status.removeClass("highlight");
        }
      };
      const checkGameState = (lastSymbol) => {
        const winLine = checkWinningLine(board, lastSymbol);
        if (winLine) {
          isGameOver = true;
          status.textContent = lastSymbol === playerSymbol ? "\u0412\u044B \u043F\u043E\u0431\u0435\u0434\u0438\u043B\u0438! \u{1F389}" : "\u0418\u0418 \u043F\u043E\u0431\u0435\u0434\u0438\u043B! \u{1F916}";
          updateStatusClass();
          winLine.forEach((idx) => cells[idx].addClass("winning"));
          if (lastSymbol === playerSymbol && this.settings.pomodoroMode) {
            this.settings.energy++;
            this.saveSettings();
          }
          return true;
        }
        if (isBoardFull(board)) {
          isGameOver = true;
          status.textContent = "\u041D\u0438\u0447\u044C\u044F! \u{1F91D}";
          updateStatusClass();
          cells.forEach((cell) => cell.addClass("draw"));
          return true;
        }
        const nextSymbol = lastSymbol === playerSymbol ? aiSymbol : playerSymbol;
        status.textContent = nextSymbol === playerSymbol ? `\u0412\u0430\u0448 \u0445\u043E\u0434 (${playerSymbol === "X" ? "\u274C" : "\u2B55"})` : `\u0425\u043E\u0434 \u0418\u0418 (${aiSymbol === "X" ? "\u274C" : "\u2B55"})...`;
        return false;
      };
      const handleCellClick = (index) => {
        if (isGameOver || isAiThinking || board[index] !== null)
          return;
        board[index] = playerSymbol;
        const cell = cells[index];
        cell.addClass("occupied");
        cell.createSpan({
          cls: `ttt-cell-symbol ${playerSymbol === "X" ? "x-color" : "o-color"}`,
          text: playerSymbol === "X" ? "\u274C" : "\u2B55"
        });
        if (checkGameState(playerSymbol))
          return;
        isAiThinking = true;
        status.textContent = `\u0418\u0418 (${aiSymbol}) \u0434\u0443\u043C\u0430\u0435\u0442...`;
        setTimeout(() => {
          if (isGameOver)
            return;
          let aiMove = -1;
          if (difficulty === "random") {
            aiMove = getRandomMove(board);
          } else if (difficulty === "smart") {
            aiMove = getSmartMove(board, aiSymbol, playerSymbol);
          } else if (difficulty === "unbeatable") {
            aiMove = getUnbeatableMove(board, aiSymbol, playerSymbol);
          }
          if (aiMove !== -1) {
            board[aiMove] = aiSymbol;
            const aiCell = cells[aiMove];
            aiCell.addClass("occupied");
            aiCell.createSpan({
              cls: `ttt-cell-symbol ${aiSymbol === "X" ? "x-color" : "o-color"}`,
              text: aiSymbol === "X" ? "\u274C" : "\u2B55"
            });
            checkGameState(aiSymbol);
          }
          isAiThinking = false;
        }, 300);
      };
      for (let i = 0; i < 9; i++) {
        const cell = boardEl.createDiv({ cls: "ttt-cell" });
        cell.addEventListener("click", () => handleCellClick(i));
        cells.push(cell);
      }
      const newGameBtn = container.createEl("button", {
        cls: "ttt-btn",
        text: "\u041D\u043E\u0432\u0430\u044F \u0438\u0433\u0440\u0430"
      });
      newGameBtn.addEventListener("click", () => {
        board = Array(9).fill(null);
        isGameOver = false;
        isAiThinking = false;
        status.textContent = `\u0412\u0430\u0448 \u0445\u043E\u0434 (${playerSymbol === "X" ? "\u274C" : "\u2B55"})`;
        updateStatusClass();
        cells.forEach((cell) => {
          cell.empty();
          cell.removeClass("occupied", "winning", "draw");
        });
      });
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TicTacToeSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Tic-Tac-Toe Brain" });
    new import_obsidian2.Setting(containerEl).setName("\u0421\u043B\u043E\u0436\u043D\u043E\u0441\u0442\u044C \u0418\u0418").setDesc("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0440\u043E\u0432\u0435\u043D\u044C \u043C\u0430\u0441\u0442\u0435\u0440\u0441\u0442\u0432\u0430 \u0432\u0441\u0442\u0440\u043E\u0435\u043D\u043D\u043E\u0433\u043E \u0418\u0418.").addDropdown((dropdown) => {
      dropdown.addOption("random", "\u0421\u043B\u0443\u0447\u0430\u0439\u043D\u044B\u0439 (\u043B\u0435\u0433\u043A\u043E)").addOption("smart", "\u0423\u043C\u043D\u044B\u0439 (\u0441\u0440\u0435\u0434\u043D\u0435)").addOption("unbeatable", "\u041D\u0435\u043F\u0440\u043E\u0438\u0433\u0440\u044B\u0432\u0430\u0435\u043C\u044B\u0439 (\u044D\u043A\u0441\u043F\u0435\u0440\u0442)").setValue(this.plugin.settings.difficulty).onChange(async (value) => {
        this.plugin.settings.difficulty = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u0421\u0438\u043C\u0432\u043E\u043B \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setDesc("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u0441\u0438\u043C\u0432\u043E\u043B, \u0437\u0430 \u043A\u043E\u0442\u043E\u0440\u044B\u0439 \u0431\u0443\u0434\u0435\u0442\u0435 \u0438\u0433\u0440\u0430\u0442\u044C \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E.").addDropdown((dropdown) => {
      dropdown.addOption("X", "\u041A\u0440\u0435\u0441\u0442\u0438\u043A (\u274C)").addOption("O", "\u041D\u043E\u043B\u0438\u043A (\u2B55)").setValue(this.plugin.settings.playerSymbol).onChange(async (value) => {
        this.plugin.settings.playerSymbol = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0439 \u0441\u0431\u0440\u043E\u0441").setDesc("\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u043D\u0430\u0447\u0438\u043D\u0430\u0442\u044C \u043D\u043E\u0432\u0443\u044E \u043F\u0430\u0440\u0442\u0438\u044E \u0447\u0435\u0440\u0435\u0437 2 \u0441\u0435\u043A\u0443\u043D\u0434\u044B \u043F\u043E\u0441\u043B\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u0438\u044F.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoReset).onChange(async (value) => {
        this.plugin.settings.autoReset = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u0420\u0435\u0436\u0438\u043C \u041F\u043E\u043C\u043E\u0434\u043E\u0440\u043E").setDesc("\u0417\u0430\u043F\u0443\u0441\u043A\u0430\u0442\u044C \u0442\u0430\u0439\u043C\u0435\u0440 \u043E\u0431\u0440\u0430\u0442\u043D\u043E\u0433\u043E \u043E\u0442\u0441\u0447\u0435\u0442\u0430 \u043F\u0440\u0438 \u0438\u0433\u0440\u0435. \u0417\u0430\u043A\u0440\u044B\u0432\u0430\u0435\u0442 \u0438\u0433\u0440\u0443 \u043F\u0440\u0438 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D\u0438\u0438.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.pomodoroMode).onChange(async (value) => {
        this.plugin.settings.pomodoroMode = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.pomodoroMode) {
      new import_obsidian2.Setting(containerEl).setName("\u0412\u0440\u0435\u043C\u044F \u0442\u0430\u0439\u043C\u0435\u0440\u0430 (\u0441\u0435\u043A\u0443\u043D\u0434\u044B)").setDesc("\u041F\u0440\u043E\u0434\u043E\u043B\u0436\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0441\u0442\u044C \u0441\u0435\u0441\u0441\u0438\u0438 \u0438\u0433\u0440\u044B/\u043E\u0442\u0434\u044B\u0445\u0430.").addText((text) => {
        text.setPlaceholder("120").setValue(this.plugin.settings.pomodoroTime.toString()).onChange(async (value) => {
          const parsedVal = parseInt(value, 10);
          if (!isNaN(parsedVal) && parsedVal > 0) {
            this.plugin.settings.pomodoroTime = parsedVal;
            await this.plugin.saveSettings();
          }
        });
      });
    }
    const energySetting = new import_obsidian2.Setting(containerEl).setName("\u041D\u0430\u043A\u043E\u043F\u043B\u0435\u043D\u043D\u0430\u044F \u044D\u043D\u0435\u0440\u0433\u0438\u044F").setDesc(`\u0412\u0430\u0448\u0430 \u043D\u0430\u043A\u043E\u043F\u043B\u0435\u043D\u043D\u0430\u044F \u044D\u043D\u0435\u0440\u0433\u0438\u044F \u0437\u0430 \u043F\u043E\u0431\u0435\u0434\u044B \u0432 \u0440\u0435\u0436\u0438\u043C\u0435 \u041F\u043E\u043C\u043E\u0434\u043E\u0440\u043E: \u26A1 ${this.plugin.settings.energy}`).addButton((btn) => {
      btn.setButtonText("\u0421\u0431\u0440\u043E\u0441\u0438\u0442\u044C \u044D\u043D\u0435\u0440\u0433\u0438\u044E").onClick(async () => {
        this.plugin.settings.energy = 0;
        await this.plugin.saveSettings();
        new import_obsidian2.Notice("\u0421\u0447\u0451\u0442\u0447\u0438\u043A \u044D\u043D\u0435\u0440\u0433\u0438\u0438 \u0441\u0431\u0440\u043E\u0448\u0435\u043D!");
        this.display();
      });
    });
  }
};
