/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DayMoodCalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/DataManager.ts
var DataManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.data = {};
  }
  async loadData() {
    const loadedData = await this.plugin.loadData();
    this.data = Object.assign({}, loadedData);
  }
  async saveData() {
    await this.plugin.saveData(this.data);
  }
  getMood(date) {
    const dateString = this.formatDate(date);
    return this.data[dateString] || null;
  }
  async setMood(date, mood) {
    const dateString = this.formatDate(date);
    this.data[dateString] = mood;
    await this.saveData();
  }
  formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
};

// src/CalendarView.ts
var import_obsidian2 = require("obsidian");

// src/MoodPickerModal.ts
var import_obsidian = require("obsidian");
var MoodPickerModal = class extends import_obsidian.Modal {
  constructor(app, date, onSelectMood) {
    super(app);
    this.date = date;
    this.onSelectMood = onSelectMood;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const dateStr = this.date.toLocaleDateString("ru-RU");
    contentEl.createEl("h2", { text: `\u041D\u0430\u0441\u0442\u0440\u043E\u0435\u043D\u0438\u0435 \u0437\u0430 ${dateStr}` });
    const container = contentEl.createDiv("mood-picker-modal-content");
    const buttonsContainer = container.createDiv("mood-picker-buttons");
    const badBtn = buttonsContainer.createEl("button", { cls: "mood-btn bad" });
    badBtn.textContent = "\u2639\uFE0F";
    badBtn.createSpan({ text: "\u041F\u043B\u043E\u0445\u043E" });
    badBtn.onclick = () => {
      this.onSelectMood("bad");
      this.close();
    };
    const normalBtn = buttonsContainer.createEl("button", { cls: "mood-btn normal" });
    normalBtn.textContent = "\u{1F610}";
    normalBtn.createSpan({ text: "\u041D\u043E\u0440\u043C\u0430\u043B\u044C\u043D\u043E" });
    normalBtn.onclick = () => {
      this.onSelectMood("normal");
      this.close();
    };
    const goodBtn = buttonsContainer.createEl("button", { cls: "mood-btn good" });
    goodBtn.textContent = "\u{1F642}";
    goodBtn.createSpan({ text: "\u0425\u043E\u0440\u043E\u0448\u043E" });
    goodBtn.onclick = () => {
      this.onSelectMood("good");
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/CalendarView.ts
var VIEW_TYPE_CALENDAR = "day-mood-calendar-view";
var CalendarView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentDate = new Date();
  }
  getViewType() {
    return VIEW_TYPE_CALENDAR;
  }
  getDisplayText() {
    return "\u041A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C \u043D\u0430\u0441\u0442\u0440\u043E\u0435\u043D\u0438\u044F";
  }
  getIcon() {
    return "calendar-days";
  }
  async onOpen() {
    this.renderCalendar();
  }
  renderCalendar() {
    const container = this.containerEl.children[1];
    if (!container)
      return;
    container.empty();
    const root = container.createDiv("day-mood-calendar-container");
    const header = root.createDiv("day-mood-calendar-header");
    const prevBtn = header.createEl("button", { text: "<" });
    prevBtn.onclick = () => {
      this.currentDate.setMonth(this.currentDate.getMonth() - 1);
      this.renderCalendar();
    };
    const monthNames = [
      "\u042F\u043D\u0432\u0430\u0440\u044C",
      "\u0424\u0435\u0432\u0440\u0430\u043B\u044C",
      "\u041C\u0430\u0440\u0442",
      "\u0410\u043F\u0440\u0435\u043B\u044C",
      "\u041C\u0430\u0439",
      "\u0418\u044E\u043D\u044C",
      "\u0418\u044E\u043B\u044C",
      "\u0410\u0432\u0433\u0443\u0441\u0442",
      "\u0421\u0435\u043D\u0442\u044F\u0431\u0440\u044C",
      "\u041E\u043A\u0442\u044F\u0431\u0440\u044C",
      "\u041D\u043E\u044F\u0431\u0440\u044C",
      "\u0414\u0435\u043A\u0430\u0431\u0440\u044C"
    ];
    const title = header.createEl("h3", {
      text: `${monthNames[this.currentDate.getMonth()]} ${this.currentDate.getFullYear()}`
    });
    const nextBtn = header.createEl("button", { text: ">" });
    nextBtn.onclick = () => {
      this.currentDate.setMonth(this.currentDate.getMonth() + 1);
      this.renderCalendar();
    };
    const grid = root.createDiv("day-mood-calendar-grid");
    const daysOfWeek = ["\u041F\u043D", "\u0412\u0442", "\u0421\u0440", "\u0427\u0442", "\u041F\u0442", "\u0421\u0431", "\u0412\u0441"];
    daysOfWeek.forEach((day) => {
      grid.createDiv({ cls: "day-mood-day-header", text: day });
    });
    const year = this.currentDate.getFullYear();
    const month = this.currentDate.getMonth();
    const firstDayOfMonth = new Date(year, month, 1);
    const lastDayOfMonth = new Date(year, month + 1, 0);
    let startDay = firstDayOfMonth.getDay();
    if (startDay === 0)
      startDay = 7;
    const daysInMonth = lastDayOfMonth.getDate();
    const today = new Date();
    for (let i = 1; i < startDay; i++) {
      grid.createDiv({ cls: "day-mood-day empty" });
    }
    for (let i = 1; i <= daysInMonth; i++) {
      const date = new Date(year, month, i);
      const dayEl = grid.createDiv({ cls: "day-mood-day" });
      dayEl.createSpan({ cls: "day-mood-day-number", text: String(i) });
      if (date.getDate() === today.getDate() && date.getMonth() === today.getMonth() && date.getFullYear() === today.getFullYear()) {
        dayEl.classList.add("today");
      }
      const mood = this.plugin.dataManager.getMood(date);
      if (mood) {
        dayEl.classList.add(`mood-${mood}`, "has-mood");
        const emojiMap = {
          bad: "\u2639\uFE0F",
          normal: "\u{1F610}",
          good: "\u{1F642}"
        };
        dayEl.createSpan({ cls: "day-mood-emoji", text: emojiMap[mood] });
      }
      dayEl.onclick = () => {
        new MoodPickerModal(this.app, date, async (selectedMood) => {
          await this.plugin.dataManager.setMood(date, selectedMood);
          this.renderCalendar();
        }).open();
      };
    }
  }
  async onClose() {
  }
};

// src/main.ts
var DayMoodCalendarPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    this.dataManager = new DataManager(this);
    await this.dataManager.loadData();
    this.registerView(
      VIEW_TYPE_CALENDAR,
      (leaf) => new CalendarView(leaf, this)
    );
    this.addRibbonIcon("calendar-days", "Day Mood Calendar", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-day-mood-calendar",
      name: "Open Calendar",
      callback: () => {
        this.activateView();
      }
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CALENDAR);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CALENDAR);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_CALENDAR, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
